/**create table EFFORT_ANALYSE (
   ID_ANALYSE_EFFORT    NUMBER                not null,
   ID_PATIENT           NUMBER                not null,
   DATE_ANALYSE_EFFORT  DATE                  not null,
   DATE_PROCHAINE_ANALYSE_EFFORT DATE,
   COMPLEMENTAIRE_EFFORT NUMBER                not null
      constraint CKC_COMPLEMENTAIRE_EF_EFFORT_A check (COMPLEMENTAIRE_EFFORT in (0,1)),
   RESULTAT_RYTHME_CARDIAQUE_AVANT NUMBER,
   RESULTAT_RYTHME_CARDIAQUE_APRES NUMBER,
   RESULTAT_RYTHME_CARDIAQUE_UNEM NUMBER,
   constraint PK_EFFORT_ANALYSE primary key (ID_ANALYSE_EFFORT)
)
/*/

create or replace trigger prediction_date_prochaine_analyse_effort before insert or update on EFFORT_ANALYSE
for each row
declare
    POBESITE NUMBER;
    PHYPERTENSION NUMBER;
    PMENOPAUSE NUMBER;
begin
     SELECT OBESITE INTO POBESITE FROM Patient WHERE Id_Patient = :new.ID_Patient;
     SELECT HYPERTENSION INTO PHYPERTENSION FROM Patient WHERE Id_Patient = :new.ID_Patient;
     SELECT MENOPAUSE INTO PMENOPAUSE FROM Patient WHERE Id_Patient = :new.ID_Patient;

    IF :new.COMPLEMENTAIRE_EFFORT = 1 then 
        IF POBESITE = 1 or PHYPERTENSION = 1 or PMENOPAUSE = 1 then
            :new.DATE_PROCHAINE_ANALYSE_EFFORT:= :new.DATE_ANALYSE_EFFORT;
        else 
            :new.DATE_PROCHAINE_ANALYSE_EFFORT:= :new.DATE_ANALYSE_EFFORT + 1;
        end if; 
    else 
        IF POBESITE = 1 or PHYPERTENSION = 1 or PMENOPAUSE = 1 then
            :new.DATE_PROCHAINE_ANALYSE_EFFORT:= :new.DATE_ANALYSE_EFFORT + 2;
        else 
            :new.DATE_PROCHAINE_ANALYSE_EFFORT:= :new.DATE_ANALYSE_EFFORT + 3;--perso normale 
        end if;    
    end if;
end ;
/

CREATE OR REPLACE PROCEDURE Peuplement_Analyse_Effort(
   PID_PATIENT NUMBER,
   PDATE_ANALYSE_EFFORT DATE,
   --DATE_PROCHAINE_ANALYSE_EFFORT DATE,
   PCOMPLEMENTAIRE_EFFORT NUMBER,
   PRESULTAT_RYTHME_CARDIAQUE_AVANT NUMBER,
   PRESULTAT_RYTHME_CARDIAQUE_APRES NUMBER,
   PRESULTAT_RYTHME_CARDIAQUE_UNEM NUMBER)
AS
    
BEGIN
    --SELECT Id_Patient INTO PIDPatient FROM Patient WHERE Id_Patient = 1;
    INSERT INTO Effort_Analyse (ID_PATIENT, Date_Analyse_effort, Complementaire_effort, RESULTAT_RYTHME_CARDIAQUE_AVANT, RESULTAT_RYTHME_CARDIAQUE_APRES, RESULTAT_RYTHME_CARDIAQUE_UNEM) 
    VALUES (PID_PATIENT, PDATE_ANALYSE_EFFORT, PCOMPLEMENTAIRE_EFFORT, PRESULTAT_RYTHME_CARDIAQUE_AVANT, PRESULTAT_RYTHME_CARDIAQUE_APRES, PRESULTAT_RYTHME_CARDIAQUE_UNEM);
    
END Peuplement_Analyse_Effort;
/

CALL Peuplement_Analyse_Effort (1,TO_DATE('22/03/2024', 'DD-MM-YYYY'), 0, 100, 100, 100);
/